# Generated by Django 5.0.6 on 2024-07-31 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='number',
            field=models.IntegerField(verbose_name='Game number'),
        ),
    ]
