# Generated by Django 5.0.6 on 2024-07-31 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_game_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='player',
            field=models.ManyToManyField(blank=True, to='myapp.player'),
        ),
    ]
