# Generated by Django 5.0.6 on 2024-07-31 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_month_remove_game_number_date_game_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='month',
            new_name='m',
        ),
        migrations.RenameField(
            model_name='month',
            old_name='month',
            new_name='month_played',
        ),
    ]
