# Generated by Django 5.0.6 on 2024-07-31 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_month_game_m_rename_month_month_month_played'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_time',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='game',
            name='number',
            field=models.CharField(max_length=20, verbose_name='Game number'),
        ),
    ]
